excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - devprojects
  - vendor
  - MUBackYard.playground

opt_in_rules:
  - unneeded_parentheses_in_closure_argument
  - switch_case_on_newline
  - strict_fileprivate
  - force_unwrapping
  - implicitly_unwrapped_optional
  - redundant_nil_coalescing
  - overridden_super_call
  - prohibited_super_call
  - private_outlet
  - strong_iboutlet
  - operator_usage_whitespace
  - no_extension_access_modifier
  - nimble_operator
  - multiline_parameters
  - let_var_whitespace
  - empty_count
  - closure_spacing
  - closure_end_indentation
  - attributes
  
identifier_name:
  min_length: 1 # only warning
